spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mytrophy-db.chqi0mcwgnzt.ap-northeast-2.rds.amazonaws.com:3306/mytrophy
    username: myt
    password: mytrophy1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: vmfhaltmsasdvdfhaertgaerfgsdfasdklfvhnsdjikonkl
